version: '3.9'

services:
  project1:
    build:
      context: .
    image: fastapi-p1-temp:v1
    working_dir: /app
    ports:
      - "9999:8000"
    volumes:
      - .:/app
    command: ["fastapi", "dev", "books.py", "--reload", "--host", "0.0.0.0", "--port", "8000"]